// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbCursosNiveles_DetailResult
    {
        public int Cun_Id { get; set; }
        public string Cun_Descripcion { get; set; }
        public string Cun_UsuarioRegistraNombre { get; set; }
        public DateTime Cun_FechaRegistra { get; set; }
        public string Cun_UsuarioModificaNombre { get; set; }
        public DateTime Cun_FechaModifica { get; set; }
    }
}
