// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbModalidades_ExistResult
    {
        public int Mda_Id { get; set; }
        public string Mda_Descripcion { get; set; }
    }
}
