// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GESTION_COLEGIAL.Entities.Entities
{
    public partial class PR_tbEventos_UpdateResult
    {
    }
}
