// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbAlumnos_ListResult
    {
        public int Alu_Id { get; set; }
        public string Per_Identidad { get; set; }
        public string Alu_Nombre { get; set; }
        public string Cno_Descripcion { get; set; }
        public string Est_Descripcion { get; set; }
    }
}
