// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbCursos_FindResult
    {
        public int Cur_Id { get; set; }
        public string Cur_Nombre { get; set; }
        public int Niv_Id { get; set; }
        public string Niv_Descripcion { get; set; }
        public bool Cur_EsActivo { get; set; }
    }
}
