// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbCargos_FindResult
    {
        public int Car_Id { get; set; }
        public string Car_Descripcion { get; set; }
    }
}
