// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbSecciones_ExistResult
    {
        public int Sec_Id { get; set; }
        public string Sec_Descripcion { get; set; }
    }
}
