// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbParciales_DetailResult
    {
        public int Pac_Id { get; set; }
        public string Pac_Descripcion { get; set; }
        public string Pac_UsuarioRegistraNombre { get; set; }
        public DateTime Pac_FechaRegistra { get; set; }
        public string Pac_UsuarioModificaNombre { get; set; }
        public DateTime Pac_FechaModifica { get; set; }
    }
}
