// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbCursosNombres_DropdownResult
    {
        public string Cno_Id { get; set; }
        public string Cno_Descripcion { get; set; }
    }
}
