// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbParciales_FindResult
    {
        public int Pac_Id { get; set; }
        public string Pac_Descripcion { get; set; }
    }
}
