// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbMaterias_FindResult
    {
        public int Mat_Id { get; set; }
        public string Mat_Nombre { get; set; }
        public string Dur_Descripcion { get; set; }
        public bool Mat_EsActivo { get; set; }
    }
}
