// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbHoras_ListResult
    {
        public int Hor_Id { get; set; }
        public string Hor_Hora { get; set; }
    }
}
