// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbEstados_ExistResult
    {
        public int Est_Id { get; set; }
        public string Est_Descripcion { get; set; }
    }
}
