// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbDias_ListResult
    {
        public int Dia_Id { get; set; }
        public string Dia_Descripcion { get; set; }
    }
}
