// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbUsuarios_List_SegurityResult
    {
        public int Usu_Id { get; set; }
        public string Per_Nombres { get; set; }
        public string Usu_Name { get; set; }
        public string Rol_Descripcion { get; set; }
    }
}
