// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbEstados_DetailResult
    {
        public int Est_Id { get; set; }
        public string Est_Descripcion { get; set; }
        public string Est_UsuarioRegistraNombre { get; set; }
        public DateTime Est_FechaRegistra { get; set; }
        public string Est_UsuarioModificaNombre { get; set; }
        public DateTime Est_FechaModifica { get; set; }
    }
}
