// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbDuraciones_DetailResult
    {
        public int? Dur_Id { get; set; }
        public string Dur_Descripcion { get; set; }
        public string Dur_UsuarioRegistraNombre { get; set; }
        public DateTime? Dur_FechaRegistra { get; set; }
        public string Dur_UsuarioModificaNombre { get; set; }
        public DateTime? Dur_FechaModifica { get; set; }
    }
}
