// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbSemestres_ListResult
    {
        public int Sem_Id { get; set; }
        public string Sem_Descripcion { get; set; }
        public string EsActivo { get; set; }
    }
}
