// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Gestion.Colegial.Commons.Entities
{
    public partial class PR_tbCursos_By_tbModalidades_DropdownResult
    {
        public int Cur_Id { get; set; }
        public string Cur_Nombre { get; set; }
    }
}
