// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Commons.Entities
{
    public partial class tbCursos_tbMaterias
    {
        public int Cur_Id { get; set; }
        public int Mat_Id { get; set; }

        public virtual tbCursos Cur { get; set; }
        public virtual tbMaterias Mat { get; set; }
    }
}